version: '3'

services:
  postgres:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
    ports:
      - 5432:5432

  api:
    container_name: api
    image: node:14
    working_dir: /usr/command
    restart: always
    command: bash -c "npm install && yarn typeorm migration:run && npm run debug"
    volumes:
      - ./dist:/usr/command/dist
      - /tmp/command/node_modules:/usr/command/node_modules
      - ./package.json:/usr/command/package.json
      - ./ormconfig.js:/usr/command/ormconfig.js
      - ./.env:/usr/command/.env
    ports:
      - 3333:3333
    links:
      - postgres
    depends_on:
      - postgres
