version: '3'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
    ports:
      - 5432:5432

  api:
    container_name: api-container
    image: node:14
    working_dir: /usr/command
    restart: always
    command: bash -c "npm install && yarn typeorm migration:run && npm run debug"
    environment:
      - APP_PORT=3333
      - DB_HOST=postgres
      - APP_HOST=192.168.0.105
    volumes:
      - ./dist:/usr/command/src
      - ./package.json:/usr/command/package.json
      - ./ormconfig.json:/usr/command/ormconfig.json
    ports:
      - 3333:3333
    links:
      - postgres
    depends_on:
      - postgres
